// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmIjrqzjkCWL7CCOnqfJv8gCn091jN5pI',
    appId: '1:214933420752:web:7d6451b433aec16911bcd5',
    messagingSenderId: '214933420752',
    projectId: 'bobo-delivery-food',
    authDomain: 'bobo-delivery-food.firebaseapp.com',
    storageBucket: 'bobo-delivery-food.firebasestorage.app',
    measurementId: 'G-ZPQ3HQXRPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBiLp0w6VEe83r1kIKrRqHaC8JboM4p4',
    appId: '1:214933420752:android:2fb3f3e17353375911bcd5',
    messagingSenderId: '214933420752',
    projectId: 'bobo-delivery-food',
    storageBucket: 'bobo-delivery-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqTSAtXHFqw0jdV41RYjfsymZxnM_17A',
    appId: '1:214933420752:ios:bdc69c7707902b2011bcd5',
    messagingSenderId: '214933420752',
    projectId: 'bobo-delivery-food',
    storageBucket: 'bobo-delivery-food.firebasestorage.app',
    androidClientId: '214933420752-tst5ppsfs00hfofajs6avadh77r8icr3.apps.googleusercontent.com',
    iosClientId: '214933420752-aa1dklt4f01o5u0jbq2mhd5gpj5co5cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.popoDeliveryDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvqTSAtXHFqw0jdV41RYjfsymZxnM_17A',
    appId: '1:214933420752:ios:bdc69c7707902b2011bcd5',
    messagingSenderId: '214933420752',
    projectId: 'bobo-delivery-food',
    storageBucket: 'bobo-delivery-food.firebasestorage.app',
    androidClientId: '214933420752-tst5ppsfs00hfofajs6avadh77r8icr3.apps.googleusercontent.com',
    iosClientId: '214933420752-aa1dklt4f01o5u0jbq2mhd5gpj5co5cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.popoDeliveryDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmIjrqzjkCWL7CCOnqfJv8gCn091jN5pI',
    appId: '1:214933420752:web:d393eb1e579dac5411bcd5',
    messagingSenderId: '214933420752',
    projectId: 'bobo-delivery-food',
    authDomain: 'bobo-delivery-food.firebaseapp.com',
    storageBucket: 'bobo-delivery-food.firebasestorage.app',
    measurementId: 'G-LFYQXPXW3M',
  );
}
